### ISSUE TITLE
[1.19.2] Soul meter exponentially increasing damage and knockback

### ISSUE THREAD

**Issue by slim-shady6** [Thelnfamous1/Dungeons-Gear#211]
From what I've observed, having a max soul meter has a chance to:

- causes your damage to exponentially increase
- increases your knockback

hence, empowering you GREATLY beyond any logical means

I am currently trying to replicate this again to show proof, but others have expressed their issues as well.

I am also using Better Combat [FORGE] alongside the Dungeons Gear

**Comment by hserranome** [comment]
I've not invested much time into trying to reproduce it but, it seems tied to equipping armor for some reason (?) It happens also with weapons and armors that are not from this mod.

**Comment by Patrigan** [comment]
Actually, the latest version of Dungeons Libraries should resolve this issue. Could you take it and verify?

**Comment by Thelnfamous1** [comment]
@hserranome @slim-shady6 Update, please. Do the latest versions still have this bug?

**Comment by Thelnfamous1** [comment]
Closing due to no further elaboration.
