### ISSUE TITLE
1.19.2 Crash on start up

### ISSUE THREAD

**Issue by ShootToKillSTK** [Thelnfamous1/Dungeons-Gear#237]
[crash-2023-04-15_19.51.56-client.txt](https://github.com/Infamous-Misadventures/Dungeons-Gear/files/11241000/crash-2023-04-15_19.51.56-client.txt)
 Not sure why crashing but just having the mod enabled causes this crash ^ disabling it lets game load to main screen like should

**Comment by ShootToKillSTK** [comment]
[crash-2023-04-15_19.56.32-client.txt](https://github.com/Infamous-Misadventures/Dungeons-Gear/files/11241011/crash-2023-04-15_19.56.32-client.txt)
crash again but fixed by removing dungeons mobs this time

**Comment by Thelnfamous1** [comment]
Fixed, re-download 5.0.5.

**Comment by ShootToKillSTK** [comment]
[crash-2023-04-20_12.24.51-client.txt](https://github.com/Infamous-Misadventures/Dungeons-Gear/files/11288903/crash-2023-04-20_12.24.51-client.txt)

still happening on startup, updated all 3 mods (dungeons library, dungeons mobs, dungeons gear)

**Comment by ShootToKillSTK** [comment]
[crash-2023-04-20_13.49.14-client.txt](https://github.com/Infamous-Misadventures/Dungeons-Gear/files/11289535/crash-2023-04-20_13.49.14-client.txt)
Nvm still happening without mod, I dont get why, I disabled a couple mods and added Essential mod and it crash, now just going back to when it was working aka reversing that stuff and it breaks .-. sigh

**Comment by Thelnfamous1** [comment]
The report cites AzureLib as the cause of the crash.
